hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
  prefix: /connect

hwi_oauth_connect:
  resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
  prefix: /connect

auth0_connect:
  path: /connect/auth0

auth0_login:
  path: /login/check-auth0

logout:
  path: /logout